### ISSUE TITLE
Wrong "storageType"

### ISSUE THREAD

**Issue by ahelmel** [grevory/angular-local-storage#158]
If localStorage and the cookies are disabled the storageType is "cookie".

**Comment by RopoMen** [comment]
My settings look like this
```javascript
 localStorageServiceProvider
            .setPrefix('myApp')
            .setStorageType('localStorage');
```

Then inside code I do
```javascript
if(!localStorageService.isSupported) {
    $log.debug('Cannot use "UserSettings" because storage type:', localStorageService.getStorageType(), ' is disabled or not supported.');
}
```
And console will show following text
'Cannot use "UserSettings" because storage type: "cookie" is disabled or not supported.'

I was expecting it to print
'Cannot use "UserSettings" because storage type: "localStorage" is disabled or not supported.'


This can be repeated easily with Chrome by changing "Content settings" and selecting "Block sites from setting any data." option.
