### ISSUE TITLE
Browser support list?

### ISSUE THREAD

**Issue by esco** [grevory/angular-local-storage#197]
Is there a list of supported browsers?

**Comment by dholcombe** [comment]
This shows which browsers support web storage. http://caniuse.com/#search=web%20storage
Since angular-local-storage falls back to cookies it should support pretty much any browser. AngularJS itself dropped IE 8 support.

As stated on the main page: "An AngularJS module that gives you access to the browsers local storage with cookie fallback  

http://gregpike.net/demos/angular-local-storage/demo.html"

**Comment by esco** [comment]
@dholcombe  thanks!
