### ISSUE TITLE
service fails when resolved by angular.injector

### ISSUE THREAD

**Issue by coryisakson** [grevory/angular-local-storage#259]
When using angular.injector to resolve the service it doesn't set or get.

http://plnkr.co/edit/rCngpgwrOq7l94uqXqJd?p=preview

**Comment by R4c00n** [comment]
There are several mistakes in the code you provided. First of all, the `config` block doesn't get executed, cause you are not initializing it with the `ng-app` attribute. That causes that, in your `loginOnFirstVisit` function, the `storageType` is still set to `localStorage` instead of your desired `sessionStorage`. 
By injecting the `LocalStorageService` by hand, it doesn't get configured, so you should use a controller instead.
Is there a special reason, why you are doing it that way?
