### ISSUE TITLE
JSON.stringify instead of angular.toJson

### ISSUE THREAD

**Issue by mkjois** [grevory/angular-local-storage#274]
The [source code](https://github.com/grevory/angular-local-storage/blob/ff233e43be10f55adc56b27a9cad0f42f3fd5675/src/angular-local-storage.js#L162-L163) and [Angular docs](https://docs.angularjs.org/api/ng/function/angular.toJson) explain limitations of  `angular.toJson`. Why not just use `JSON.stringify` when serializing for a set? You already use `JSON.parse` to deserialize on a get.

**Comment by rajkumarpb** [comment]
Let me check that from my fork and see if that works!!

**Comment by ealves-pt** [comment]
@mkjois I don't think the differences between ```angular.toJson|angular.fromJson``` and ```JSON.stringify|JSON.parse``` are relatively small.

Basically the ```angular``` methods are wrappers for ```JSON``` methods and their behaviour it's pretty much the same since [v1.2.0](https://github.com/angular/angular.js/blob/v1.2.0/src/Angular.js#L935).

The only thing special to note is that ```angular.toJson``` does a bit of a cleanup and for each key inside an object that starts with ```$``` the value is set to ```undefined``` unless it's ```$window, $scope, $document``` in those cases the values stored are ```'$WINDOW', '$SCOPE', '$DOCUMENT'``` respectively.
@mkjois I don't think the differences between ```angular.toJson|angular.fromJson``` and ```JSON.stringify|JSON.parse``` are relatively small.

Basically the ```angular``` methods are wrappers for ```JSON``` methods and their behaviour it's pretty much the same since [v1.2.0](https://github.com/angular/angular.js/blob/v1.2.0/src/Angular.js#L935).

The only thing special about ```angular.toJson``` is that any key that starts with ```$``` the value is set to ```undefined``` unless it is ```$window, $scope, $document``` in those cases the values stored are ```'$WINDOW', '$SCOPE', '$DOCUMENT'``` respectively.

Regarding that comment in the source code I can't actually understand the problem because in every test that I made the results of ```angular.toJson``` are the same as ```JSON.stringify```.

```javascript
var ws = angular.element(document.body).injector().get('$window')['sessionStorage'];
ws.get('non_existing_key'); // null

ws.setItem('key.nullVal.toJson', angular.toJSON(null));
ws.setItem('key.nullVal.Json.stringify', JSON.stringify(null));
ws.getItem('key.nullVal.toJson'); // 'null'
ws.getItem('key.nullVal.Json.stringify'); // 'null'

ws.setItem('key.nullStr.toJson', angular.toJSON('null'));
ws.setItem('key.nullStr.Json.stringify', JSON.stringify('null'));
ws.getItem('key.nullStr.toJson'); // "'null'"
ws.getItem('key.nullStr.Json.stringify'); // "'null'"
```

Perhaps I am missing some use case. In my opinion, because this library depends on angular we should use ```angular.toJson``` and ```angular.fromJson``` to make sure we don't mess up anything storing in session and entire ```$scope``` object.
